### ISSUE TITLE
prometheus: can't add query

### ISSUE THREAD

**Issue by brunoqc** [grafana/grafana-plugins#39]
Nothing happens when I click the "+ Query" button.

I don't see any error in the log nor in the javascript console.

I'm using the latest code from grafana and grafana-plugins.

**Comment by Amnacog** [comment]
Confirmed, but this is a grafana related issue not grafana-plugins try the [v2.1.x branch of grafana]
(https://github.com/grafana/grafana/tree/v2.1.x)

It worked for me

**Comment by brunoqc** [comment]
It works with the v2.1.x branch. Thanks!

Do you know if the issue was already reported on the Grafana's issues tracker?

**Comment by mtanda** [comment]
The problem might be fixed in this PR.

https://github.com/grafana/grafana-plugins/pull/37

**Comment by mtanda** [comment]
@torkelo Would merge this PR?

**Comment by mtanda** [comment]
Ah, I notice that it doesn't work correctly.
Sorry, I'll fix it.

**Comment by mtanda** [comment]
I fixed it.

**Comment by xbglowx** [comment]
With commit 06d701d2f188b6bbcd163b829c37b6ed17dcd1b2, I can no longer view existing queries under metrics. 27f1398b497650f5b10b983ab9507665095a71b3.zip is the last working commit.

Working now with:
granfana: 2.1.3
granfana plugin: 27f1398b497650f5b10b983ab9507665095a71b3
prometheus 0.15.1

**Comment by mtanda** [comment]
Sorry, latest version only work with mixed datasource support.
The version 2.1.3 doesn't support mixed datasource.

There is no mixed datasource code at 2.1.3.
https://github.com/grafana/grafana/tree/v2.1.3/public/app/plugins/datasource

(The mixed datasource code is merged to master at this commit.
https://github.com/grafana/grafana/commit/9a9c9b2b121d5b3bf93cf589b31f377ab9f4b10c)

So, please use old plugin code until Grafana next release.

**Comment by tgulacsi** [comment]
I'm using this script to build grafana master with latest grafana-plugins:
```
ExecStartPre=/bin/sh -c 'echo -e "FROM grafana/grafana\nMAINTAINER Tamás Gulácsi <T.Gulacsi@unosoft.hu>\nENV DPKG_FRONTEND=noninteractive\nRUN apt-get install -y unzip rsync\nRUN wget https://grafanarel.s3.amazonaws.com/builds/grafana_latest_amd64.deb\nRUN dpkg -i grafana_latest_amd64.deb\nRUN wget -O /tmp/grafana-plugins.zip https://github.com/grafana/grafana-plugins/archive/master.zip\nRUN cd /tmp && unzip grafana-plugins.zip\nRUN find /tmp/grafana-plugins-master && rsync -avz /tmp/grafana-plugins-master/datasources/ /usr/share/grafana/public/app/plugins/datasource/" | docker build -t tgulacsi/grafana -'
```

But still can't add prometheus metric.

**Comment by iwinux** [comment]
Same problem here, with Grafana 2.1.3.

Downgraded grafana-plugins to commit 57055f72c4745abe6c33a26359ebfb6e59920345 and it works...

**Comment by mtanda** [comment]
@tgulacsi
It's strange. I'm using Grafana on Mac OS X.
I confirmed the plugin work at following environment.
grafana: https://github.com/grafana/grafana/commit/2b95cd5081f046f904a30aeacae0297569b531b6
grafana-plugins: https://github.com/grafana/grafana-plugins/commit/47351473822ec4885d4fb0a57d5c7453718e4045
I'll try to reproduce by using Linux and latest deb.

@iwinux
> There is no mixed datasource code at 2.1.3.
> https://github.com/grafana/grafana/tree/v2.1.3/public/app/plugins/datasource

The latest plugin doesn't work at 2.1.3...

**Comment by mtanda** [comment]
@tgulacsi 
I setup Grafana by docker, and try to reproduce.
But I can't reproduce the bug, it works correctly.

![grafana](https://cloud.githubusercontent.com/assets/224552/9924814/117157da-5d3e-11e5-8b51-7e0aeece949d.png)

This is my Dockerfile, I copied from your setup sequence.
https://github.com/mtanda/grafana-docker/commit/465ca855a7d248979cee6a0b2782f635f8f64b6b

And, I disable browser cache by opening Chrome Developer Tools.

**Comment by tgulacsi** [comment]
Strange. With disabled cache, I can still see the "+ Query" button but not
the queries when using grafana-master with the grafana-plugins-master, but
everything works with grafana 2.1.3 and grafana-plugins
@57055f72c4745abe6c33a26359ebfb6e59920345

Shall I provide access to my grafana / prometheus server for you to
investigate further, or just stick with what's working and try again with
the next releases?

---
https://onename.com/tgulacsi

2015-09-17 6:19 GMT+02:00 Mitsuhiro Tanda <notifications@github.com>:

**Comment by stapelberg** [comment]
I just ran into the same problem.

@mtanda I’m also using docker to run grafana:

```bash
docker run -v /media/persistent/grafana/lib:/var/lib/grafana \
-v /media/persistent/grafana/grafana-plugins/datasources/prometheus:/usr/share/grafana/public/app/plugins/datasource/prometheus \
-p 127.0.0.1:3000:3000 \
 --link prometheus:prometheus \
grafana/grafana
```

**Comment by alexanderzobnin** [comment]
It seems this bug in latest Grafana version (I tried on last version from sources: `Version: 2.5.0-pre1, Commit: v2.1.2+358-ga7cc36f1`). I looked at the plugins sources and seen that in this version `query.editor.html` has bit differencese from previos version. I will try to resolve problem in my datasource and then report result.

**Comment by mtanda** [comment]
@tgulacsi 
I'm not sure whether I can fix it, if I can access your environment.
So I'll check mixed data source code when I have time.

@alexanderzobnin 
It's great help. Thanks!

**Comment by alexanderzobnin** [comment]
@mtanda see more about breaking changes in Grafana 2.2: https://github.com/grafana/grafana/blob/master/docs/sources/datasources/plugin_api.md

**Comment by mtanda** [comment]
@alexanderzobnin 
Thanks good info :)

I can't reproduce bug yet.
But, I notice that there are unmatched tags in partial html.
I fixed it in this PR.
https://github.com/grafana/grafana-plugins/pull/43

**Comment by mtanda** [comment]
And, I notice that Grafana 2.5 has more breaking changes.
We need to fix datasource plugin.

I start to work for that in this PR.
https://github.com/grafana/grafana-plugins/pull/44

**Comment by ajankovic** [comment]
For me this issue is local to Firefox.

![metrics_prometheus](https://cloud.githubusercontent.com/assets/509084/10159006/eab9f816-6695-11e5-8dd6-f583394ad423.png)

 With Chromium form is visible.

![chrome_prometheus](https://cloud.githubusercontent.com/assets/509084/10159127/bccf65ac-6696-11e5-8388-e19e0b4e4f32.png)

**Comment by TheHippo** [comment]
Having the same issue.

Grafana version: 2.1.3
Plugins: current git master

**Comment by roman-vynar** [comment]
Temporary workaround until new grafana release:
```
git clone https://github.com/grafana/grafana-plugins.git
cd grafana-plugins
git reset --hard 57055f7
rm -rf /usr/share/grafana/public/app/plugins/datasource/prometheus
cp -a datasources/prometheus /usr/share/grafana/public/app/plugins/datasource/
```
Than clear browser cache, this is important.

**Comment by TheHippo** [comment]
@roman-vynar: thank you. This works for me. :+1:

**Comment by mtanda** [comment]
Integration process, to official release, is in progress.
https://github.com/grafana/grafana/tree/prometheus

I can't reproduce the issue yet.
If someone who met the issue, please try to reproduce at the branch.

**Comment by brunoqc** [comment]
The `prometheus` branch works for me. :+1:

**Comment by mtanda** [comment]
Thanks for testing :+1:

**Comment by fgeller** [comment]
+1

**Comment by qzio** [comment]
:+1:

**Comment by brasslock** [comment]
I did have this issue when using Grafana 2.1.3.
Now using Grafana 2.5.0 it works fine.
Thanks.
